code --install-extension aaron-bond.better-comments
code --install-extension abusaidm.html-snippets
code --install-extension andys8.jest-snippets
code --install-extension castwide.solargraph
code --install-extension ChakrounAnas.turbo-console-log
code --install-extension christian-kohler.npm-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension cssho.vscode-svgviewer
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension eg2.tslint
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension firsttris.vscode-jest-runner
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.code-runner
code --install-extension golang.go
code --install-extension HookyQR.beautify
code --install-extension jchannon.csharpextensions
code --install-extension joelday.docthis
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension kleber-swf.unity-code-snippets
code --install-extension lionize.unity-snippets-modified
code --install-extension Mikael.Angular-BeastCode
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension mtxr.sqltools
code --install-extension naumovs.theme-oceanicnext
code --install-extension octref.vetur
code --install-extension Orta.vscode-jest
code --install-extension pnp.polacode
code --install-extension pucelle.vscode-css-navigation
code --install-extension rebornix.ruby
code --install-extension robinbentley.sass-indented
code --install-extension rvest.vs-code-prettier-eslint
code --install-extension shinnn.stylelint
code --install-extension steoates.autoimport
code --install-extension stevejpurves.cucumber
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension Tobiah.unity-tools
code --install-extension Unity.unity-debug
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension waderyan.gitblame
code --install-extension WallabyJs.quokka-vscode
code --install-extension wayou.vscode-todo-highlight
code --install-extension wingrunr21.vscode-ruby
code --install-extension wix.vscode-import-cost
code --install-extension wmaurer.vscode-jumpy
code --install-extension xabikos.JavaScriptSnippets
code --install-extension xabikos.ReactSnippets
code --install-extension xyz.local-history
code --install-extension Zignd.html-css-class-completion
